/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sc_delay_corr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fdab94dc1851dd8ada13d5c58b162fe9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <xfdm_sync/sc_delay_corr.h>
// pydoc.h is automatically generated in the build directory
#include <sc_delay_corr_pydoc.h>

void bind_sc_delay_corr(py::module& m)
{

    using sc_delay_corr = gr::xfdm_sync::sc_delay_corr;


    py::class_<sc_delay_corr,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<sc_delay_corr>>(m, "sc_delay_corr", D(sc_delay_corr))

        .def(py::init(&sc_delay_corr::make),
             py::arg("seq_len"),
             py::arg("normalize"),
             D(sc_delay_corr, make))


        ;
}
