/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sync_tag_align_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4947bf825712e40f5543404ebbecc0b5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <xfdm_sync/sync_tag_align_cc.h>
// pydoc.h is automatically generated in the build directory
#include <sync_tag_align_cc_pydoc.h>

void bind_sync_tag_align_cc(py::module& m)
{

    using sync_tag_align_cc = gr::xfdm_sync::sync_tag_align_cc;


    py::class_<sync_tag_align_cc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<sync_tag_align_cc>>(
        m, "sync_tag_align_cc", D(sync_tag_align_cc))

        .def(py::init(&sync_tag_align_cc::make),
             py::arg("num_inputs"),
             py::arg("tag_key"),
             D(sync_tag_align_cc, make))


        ;
}
